name: Auto Update HeroZero

on:
  schedule:
    - cron: '*/1 * * * *' # كل دقيقة
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update File
        run: |
          echo '{
            "recommendations": [],
            "updates": [],
            "high_priority": []
          }' > herozero.json

      - name: Commit changes
        run: |
          git config --global user.name "herodev-auto"
          git config --global user.email "herodev-auto@example.com"
          git add herozero.json
          git commit -m "Auto update herozero.json" || echo "No changes to commit"
          git push
