name: Auto Update HeroZero

on:
  schedule:
    - cron: '*/1 * * * *'  # يحدث كل دقيقة
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update File
        run: |
          echo '{
            "recommendations": [],
            "updates": [],
            "high_priority": []
          }' > herozero.json

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add herozero.json
          git commit -m "Auto update herozero.json"
          git push
