name: تحديث تلقائي لملف HeroZero

on:
  schedule:
    - cron: "*/1 * * * *"  # يحدث كل دقيقة
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: جلب الكود
        uses: actions/checkout@v3

      - name: تحديث ملف JSON
        run: |
          echo '{
            "recommendations": [
              {
                "symbol": "MSFT",
                "type": "Call",
                "contract": "APR 11 400C",
                "entry_condition": "كسر مقاومة",
                "entry": 1.25,
                "targets": [1.80, 2.50],
                "stop_loss": 1.00,
                "reason": "زخم صاعد قوي"
              }
            ],
            "updates": [],
            "high_priority": []
          }' > herozero.json

      - name: رفع التعديلات
        run: |
          git config --global user.name "HeroBot"
          git config --global user.email "herobot@example.com"
          git add herozero.json
          git commit -m "تحديث تلقائي"
          git push
